apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: lambdadevcustomer 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lambdadevcustomer 
    spec:
      containers:
        - name: lambdadevcustomer 
          image: admin22acr.azurecr.io/lambdadevcustomer
          ports:
          - containerPort: 8080